### ISSUE TITLE
Enhance CSS with Responsive Design and Mobile Support

### ISSUE THREAD

**Issue by kjanat** [kjanat/mkdocs-exam#25]
## Description
Add responsive design features to make the exam plugin work better on mobile devices and tablets.

## Proposed Changes
- Implement mobile-first responsive design with breakpoints
- Adjust padding, margins, and button sizes for smaller screens
- Ensure touch-friendly interface elements
- Add responsive fieldset and form styling

## Example Implementation
```css
@media (max-width: 768px) {
  .exam {
    padding: 0.75rem;
    margin: 0.75rem 0;
  }
  
  fieldset {
    gap: 0.5rem;
  }
  
  form button {
    width: 100%;
    padding: 0.75rem;
  }
}
```

## Acceptance Criteria
- [ ] Exam interface works well on mobile devices (320px+)
- [ ] Buttons and form elements are touch-friendly
- [ ] Content remains readable on small screens
- [ ] No horizontal scrolling on mobile devices

## Priority
Medium

## Labels
enhancement, css, responsive, mobile
