### ISSUE TITLE
Add CSS Animations and Smooth Transitions

### ISSUE THREAD

**Issue by kjanat** [kjanat/mkdocs-exam#26]
## Description
Add smooth animations and transitions to enhance the user experience when interacting with exam elements.

## Proposed Changes
- Add transition effects for state changes (correct/wrong answers)
- Implement smooth reveal animations for feedback
- Add hover and focus transitions for better interactivity
- Create loading animations for dynamic content

## Example Implementation
```css
.exam {
  transition: border-color 0.2s ease;
}

.hidden {
  opacity: 0;
  transform: translateY(-10px);
  transition: all 0.3s ease;
}

.exam input, .exam textarea, .exam select {
  transition: border-color 0.2s ease, box-shadow 0.2s ease;
}

.feedback {
  animation: slideIn 0.3s ease-out;
}

@keyframes slideIn {
  from {
    opacity: 0;
    transform: translateY(-10px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}
```

## Acceptance Criteria
- [ ] Smooth transitions for all state changes
- [ ] Feedback appears with animation
- [ ] No jarring visual changes
- [ ] Animations are performant and not distracting
- [ ] Respect user preferences for reduced motion

## Priority
Low

## Labels
enhancement, css, animation, ux
